version: '3.8'
services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    command: postgres -c fsync=off -c full_page_writes=off 
  
  postgres-local:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: development_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-local-data:/var/lib/postgresql/data

volumes:
  postgres-local-data: 